### ISSUE TITLE
IG refresh triggers cleanData

### ISSUE THREAD

**Issue by grlicaa** [RonnyWeiss/Apex-Fancy-Tree-Select#16]
Hi Ronny,

first of all thank you for this useful plug-in.  We have  set up plugin  in APEX 22.1 and all works great until there is an IG on the same page.
Loading works, but when you try to refresh IG, set filter, or any "refresh" action on IG at that point Fancytree plugin get following error :

  Error in action for 'search'. TypeError: Cannot read properties of null (reading 'tooltip')
    at c.<computed>.element.<computed>.d.remove (desktop_all.min.js?v=21.2.9:34:15314)
    at HTMLTableCellElement.h (desktop_all.min.js?v=21.2.9:29:12125)
    at HTMLTableCellElement.dispatch (desktop_all.min.js?v=21.2.9:2:43064)
    at v.handle (desktop_all.min.js?v=21.2.9:2:41048)
    at Object.trigger (desktop_all.min.js?v=21.2.9:2:71515)
    at S.fn.init.triggerHandler (desktop_all.min.js?v=21.2.9:2:72194)
    **at k.cleanData (fancytree.pkgd.min.js:1:231)**
    at a.cleanData (jetCommonBundle.min.js?v=21.2.9:209:50636)
    at S.fn.init.empty (desktop_all.min.js?v=21.2.9:2:50317)
    at k.<computed>.<computed>.refresh (interactiveGrid.min.js?v=21.2.9:7:24298)
    
So clearly something was triggered during "refresh" event. (I assure you there is  no JS or any action added from our side to trigger anything on plug-in region).

With further investigation I found that this part of code is triggered :

file js/lib/jquery.fancytree-all-deps.js

```
$.cleanData = ( function( orig ) {
		return function( elems ) {
			var events, elem, i;
			for ( i = 0; ( elem = elems[ i ] ) != null; i++ ) {

				// Only trigger remove when necessary to save time
				events = $._data( elem, "events" );
				if ( events && events.remove ) {
					$( elem ).triggerHandler( "remove" );
				}
			}
			orig( elems );
		};
	} )( $.cleanData );
```
When I remove this part of code, plugin works without problem. Please check plugin, and suggest what can be workaround for this issue.

Plugin is unusable with IG on the same page at the moment. 

Thank you,
Kind regards,
Andrej Grlica

**Comment by McRange** [comment]
Look at [Fancytree Wiki](https://github.com/mar10/fancytree/wiki): you have to use `jquery.fancytree-all.min.js` instead of `jquery.fancytree-all-deps.min.js`, when your project is already includes jQuery UI. 
APEX integrates jQuery UI, so you have to prevent the functions from being overwritten.

I have found a workaround:
So [download jquery.fancytree-all.js](https://github.com/mar10/fancytree/blob/master/dist/jquery.fancytree-all.js) from Github and replace `jquery.fancytree-all-deps.min.js` in the `js/lib` folder.
Then follow instructions in gulpfile.js to install gulp and execute
`gulp concatmainjs`

Upload the patched `build\fancytree.pkgd.min.js` to the APEX FancyTree Plugin and the cleanData bug is gone.
However, I cannot say whether all the functions of the Fancy Tree will still be supported. Ronny can certainly evaluate that better than I can
