### ISSUE TITLE
enabled Debounce feature causing empty target items on page load

### ISSUE THREAD

**Issue by McRange** [RonnyWeiss/Apex-Fancy-Tree-Select#7]
There is a major bug caused by the debounce feature:

If a fast clicking user opens a page with the fancy tree and immediately  submits the page without changing something BEFORE the debounce timer elapsed and writes the value to the designated page item, then value is empty / NULL.
In this case, the user may accidentally delete the content.

A possible solution would be to write the value of the item directly when initializing the plugin, without executing further dynamic actions. If the debounce feature is activated, the item will be triggered again after the time has elapsed.

**Comment by RonnyWeiss** [comment]
Hello Matthias

Thank you for your issue! Quick question - by debounce do you mean lazy loading (asynchronous loading) of the tree or what do you mean by debounce?

If yes, then it would only be possible to disable lazy loading, but this would lead to a delay in loading the APEX page in case of long query runtimes. 

Would it be a solution for you if I would include events, e.g. Tree Rendered or After Refresh, so that you get a trigger when the tree is finished loading. This way you get the possibility that as long as this trigger is not fired you simply prevent e.g. the accidental saving?

Kind regards

Ronny

**Comment by McRange** [comment]
sorry, I had received incomplete information from colleagues. One colleague had fixed the actual cause in the background, while another was still reporting the problem. 
The solution is not only to set the attribute "setItemsOnInit" in ConfigJSON, but to set the item values already before loading the page with a SQL statement.

**Comment by RonnyWeiss** [comment]
That's also possible! :-) I will add a switch to the next update anyway, so that you get before and after refresh also when loading. So you have more possibilities!
